### ISSUE TITLE
[Feat] Add Auto-login method (with Seleium)

### ISSUE THREAD

**Issue by gunyu1019** [gunyu1019/chzzkpy#23]
## Describe the new feature<br/>
Add automatic login feature with seleium webdriver

## TODO<br/>
- [ ] Add `login_web(driver_name)` method
- [ ] Add feature to get cookie variable (NID_AUT, NID_SES)
- [ ] Add extras required package (calls [auto_auth])

**Comment by gunyu1019** [comment]
This issue had canceled to support offical API ( #42 )
