### ISSUE TITLE
[Docs] Package Docs

### ISSUE THREAD

**Issue by gunyu1019** [gunyu1019/chzzkpy#29]
## Describe the new feature<br/>
Work on package chzzkpy docs

## TODO<br/>
- [x] Add `Basic Feature` page
  - [x] Add `Client` contents
  - [x] Add `Data Class` contents
  - [x] Add `Exception` contents
- [x] Add `Chat Feature` page
  - [x] Add `Client` contents
  - [x] Add `Event Handler` contents
  - [x] Add `Data Class` contents
  - [x] Add `Exception` contents
- [x] Add `Example` page
- [x] Add korean content (docstring language is english)
- [x] Implement document Continious Deployment with github pages

**Comment by gunyu1019** [comment]
Done. ('24.11.15. 01:25)

**Last TODO, before Pull Request**
- [ ] Setup github-action (Document build / deployment) condition.
- [ ] Add interaction button translation (en <-> ko)
- [ ] Base URL redirect to korean Document.
